### ISSUE TITLE
[BUG] tensorclass as the inputs of torch.vmap

### ISSUE THREAD

**Issue by Mary-Tim** [pytorch/tensordict#823]
## Describe the bug

Hi expert,

I'm using the tensorclass as the data type in my self-defined nn.Module.
But I get a problem when I try to use the torch.vmap to vectorize some calculations.

The minimal script to reproduce the problem:

```python
import torch
from tensordict.prototype import tensorclass

@tensorclass
class Data:
    a: torch.Tensor
    b: torch.Tensor

def AplusB(data):
    return data.a+data.b

data = Data(a=torch.randn(10), b=torch.randn(10), batch_size=[10])
result = torch.vmap(AplusB)(data)
print(result)
```
I get the error:
```
Traceback (most recent call last):
  File "---", line 20, in <module>
    result = torch.vmap(AplusB)(data)
  File "---/torch/_functorch/apis.py", line 188, in wrapped
    return vmap_impl(func, in_dims, out_dims, randomness, chunk_size, *args, **kwargs)
  File "---/torch/_functorch/vmap.py", line 273, in vmap_impl
    batch_size, flat_in_dims, flat_args, args_spec = _process_batched_inputs(in_dims, args, func)
  File "---/tensordict/nn/functional_modules.py", line 199, in _process_batched_inputs
    raise ValueError(
ValueError: vmap(AplusB, in_dims=0, ...)(<inputs>):
Got in_dim=0 for an input but the input is of type
<class '__main__.Data'>. We cannot vmap over non-Tensor arguments,
please use None as the respective in_dim
```

While the TensorDict seems to work well:
```python
import torch
from tensordict import TensorDict

data = TensorDict({
    "a": torch.randn(10),
    "b": torch.randn(10),
}, batch_size=[10])

def AplusB(data):
    return data['a']+data['b']

result = torch.vmap(AplusB)(data)
print(result)
# tensor([-0.3984, -1.1848, -1.7886, -0.2535, -2.5161,  1.3388,  0.2267, -2.6872, 2.7387, -0.1511])
```

As I want to add some member functions in the data class, I do need to use the tensorclass instead of TensorDict.
How can I solve this problem?

## System info

```python
import tensordict, numpy, sys, torch
print(tensordict.__version__, numpy.__version__, sys.version, sys.platform, torch.__version__)
# 0.4.0 1.26.1 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0] linux 2.3.1+cu121
```

**Comment by busFred** [comment]
However, things fall apart when `chunk_size` is set to anything else. I think this remains a bug though.
```python
import torch
from tensordict import tensorclass

@tensorclass
class Data:
    a: torch.Tensor
    b: torch.Tensor

def AplusB(data):
    return data.a+data.b

data = Data(a=torch.randn(10), b=torch.randn(10), batch_size=[10])
result = torch.vmap(AplusB, chunk_size=1)(data)
print(result)
```
